// @generated by protoc-gen-es v1.5.0 with parameter "target=ts"
// @generated from file coreum/customparams/v1/genesis.proto (package coreum.customparams.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { StakingParams } from "./params_pb.js";

/**
 * GenesisState defines the module's genesis state.
 *
 * @generated from message coreum.customparams.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * staking_params defines staking parameters of the module.
   *
   * @generated from field: coreum.customparams.v1.StakingParams staking_params = 1;
   */
  stakingParams?: StakingParams;

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "coreum.customparams.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "staking_params", kind: "message", T: StakingParams },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

