// @generated by protoc-gen-es v1.5.0 with parameter "target=ts"
// @generated from file coreum/customparams/v1/tx.proto (package coreum.customparams.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { StakingParams } from "./params_pb.js";

/**
 * @generated from message coreum.customparams.v1.MsgUpdateStakingParams
 */
export class MsgUpdateStakingParams extends Message<MsgUpdateStakingParams> {
  /**
   * @generated from field: string authority = 1;
   */
  authority = "";

  /**
   * staking_params holds the parameters related to the staking module.
   *
   * @generated from field: coreum.customparams.v1.StakingParams staking_params = 2;
   */
  stakingParams?: StakingParams;

  constructor(data?: PartialMessage<MsgUpdateStakingParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "coreum.customparams.v1.MsgUpdateStakingParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "authority", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "staking_params", kind: "message", T: StakingParams },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgUpdateStakingParams {
    return new MsgUpdateStakingParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgUpdateStakingParams {
    return new MsgUpdateStakingParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgUpdateStakingParams {
    return new MsgUpdateStakingParams().fromJsonString(jsonString, options);
  }

  static equals(a: MsgUpdateStakingParams | PlainMessage<MsgUpdateStakingParams> | undefined, b: MsgUpdateStakingParams | PlainMessage<MsgUpdateStakingParams> | undefined): boolean {
    return proto3.util.equals(MsgUpdateStakingParams, a, b);
  }
}

/**
 * @generated from message coreum.customparams.v1.EmptyResponse
 */
export class EmptyResponse extends Message<EmptyResponse> {
  constructor(data?: PartialMessage<EmptyResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "coreum.customparams.v1.EmptyResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EmptyResponse {
    return new EmptyResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EmptyResponse {
    return new EmptyResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EmptyResponse {
    return new EmptyResponse().fromJsonString(jsonString, options);
  }

  static equals(a: EmptyResponse | PlainMessage<EmptyResponse> | undefined, b: EmptyResponse | PlainMessage<EmptyResponse> | undefined): boolean {
    return proto3.util.equals(EmptyResponse, a, b);
  }
}

