// @generated by protoc-gen-es v1.5.0 with parameter "target=ts"
// @generated from file coreum/feemodel/v1/params.proto (package coreum.feemodel.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * ModelParams define fee model params.
 * There are four regions on the fee model curve
 * - between 0 and "long average block gas" where gas price goes down exponentially from InitialGasPrice to gas price with maximum discount (InitialGasPrice * (1 - MaxDiscount))
 * - between "long average block gas" and EscalationStartBlockGas (EscalationStartBlockGas = MaxBlockGas * EscalationStartFraction) where we offer gas price with maximum discount all the time
 * - between EscalationStartBlockGas (EscalationStartBlockGas = MaxBlockGas * EscalationStartFraction) and MaxBlockGas where price goes up rapidly (being an output of a power function) from gas price with maximum discount to MaxGasPrice  (MaxGasPrice = InitialGasPrice * MaxGasMultiplier)
 * - above MaxBlockGas (if it happens for any reason) where price is equal to MaxGasPrice (MaxGasPrice = InitialGasPrice * MaxGasMultiplier)
 *
 * The input (x value) for that function is calculated by taking short block gas average.
 * Price (y value) being an output of the fee model is used as the minimum gas price for next block.
 *
 * @generated from message coreum.feemodel.v1.ModelParams
 */
export class ModelParams extends Message<ModelParams> {
  /**
   * initial_gas_price is used when block gas short average is 0. It happens when there are no transactions being broadcasted. This value is also used to initialize gas price on brand-new chain.
   *
   * @generated from field: string initial_gas_price = 1;
   */
  initialGasPrice = "";

  /**
   * max_gas_price_multiplier is used to compute max_gas_price (max_gas_price = initial_gas_price * max_gas_price_multiplier). Max gas price is charged when block gas short average is greater than or equal to MaxBlockGas. This value is used to limit gas price escalation to avoid having possible infinity GasPrice value otherwise.
   *
   * @generated from field: string max_gas_price_multiplier = 2;
   */
  maxGasPriceMultiplier = "";

  /**
   * max_discount is th maximum discount we offer on top of initial gas price if short average block gas is between long average block gas and escalation start block gas.
   *
   * @generated from field: string max_discount = 3;
   */
  maxDiscount = "";

  /**
   * escalation_start_fraction defines fraction of max block gas usage where gas price escalation starts if short average block gas is higher than this value.
   *
   * @generated from field: string escalation_start_fraction = 4;
   */
  escalationStartFraction = "";

  /**
   * max_block_gas sets the maximum capacity of block. This is enforced on tendermint level in genesis configuration. Once short average block gas goes above this value, gas price is a flat line equal to MaxGasPrice.
   *
   * @generated from field: int64 max_block_gas = 5;
   */
  maxBlockGas = protoInt64.zero;

  /**
   * short_ema_block_length defines inertia for short average long gas in EMA model. The equation is: NewAverage = ((ShortAverageBlockLength - 1)*PreviousAverage + GasUsedByCurrentBlock) / ShortAverageBlockLength
   * The value might be interpreted as the number of blocks which are taken to calculate the average. It would be exactly like that in SMA model, in EMA this is an approximation.
   *
   * @generated from field: uint32 short_ema_block_length = 6;
   */
  shortEmaBlockLength = 0;

  /**
   * long_ema_block_length defines inertia for long average block gas in EMA model. The equation is: NewAverage = ((LongAverageBlockLength - 1)*PreviousAverage + GasUsedByCurrentBlock) / LongAverageBlockLength
   * The value might be interpreted as the number of blocks which are taken to calculate the average. It would be exactly like that in SMA model, in EMA this is an approximation.
   *
   * @generated from field: uint32 long_ema_block_length = 7;
   */
  longEmaBlockLength = 0;

  constructor(data?: PartialMessage<ModelParams>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "coreum.feemodel.v1.ModelParams";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "initial_gas_price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "max_gas_price_multiplier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "max_discount", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "escalation_start_fraction", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "max_block_gas", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "short_ema_block_length", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 7, name: "long_ema_block_length", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ModelParams {
    return new ModelParams().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ModelParams {
    return new ModelParams().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ModelParams {
    return new ModelParams().fromJsonString(jsonString, options);
  }

  static equals(a: ModelParams | PlainMessage<ModelParams> | undefined, b: ModelParams | PlainMessage<ModelParams> | undefined): boolean {
    return proto3.util.equals(ModelParams, a, b);
  }
}

/**
 * Params store gov manageable feemodel parameters.
 *
 * @generated from message coreum.feemodel.v1.Params
 */
export class Params extends Message<Params> {
  /**
   * model is a fee model params.
   *
   * @generated from field: coreum.feemodel.v1.ModelParams model = 1;
   */
  model?: ModelParams;

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "coreum.feemodel.v1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "model", kind: "message", T: ModelParams },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

